// Список пустой техники [название, класс]
// СЛЕДИТЕ ЗА ЗАПЯТЫМИ!!!
[
	["Газ-233011","rhs_tigr_v"],
	["Внедорожник с ДШК","B_G_Offroad_01_armed_F"],
	["Урал-4320","RHS_Ural_MSV_01"],
	["Газ-66","rhs_gaz66_msv"],
	["БМП-2","rhs_bmp2_msv"],
	["БТР-80","rhs_btr80_msv"],
	["Т-80Б","rhs_t80b"],
	["Т-80","rhs_t80"],
	["Т-80А","rhs_t80a"],
	["ОБТ-52","I_MBT_03_cannon_F"],
	["М2А1","B_MBT_01_cannon_F"],
	["ЗСУ-23-4B","rhs_zsu234_aa"],
	["ЗУ Тигр","O_APC_Tracked_02_AA_F"],
	["AFV-4 Горгона","I_APC_Wheeled_03_cannon_F"],
	["Касатка","O_Heli_Light_02_unarmed_F"],
	["UH-80","B_Heli_Transport_01_F"],
	["CH-49","I_Heli_Transport_02_F"],
	["AH-9","B_Heli_Light_01_armed_F"],
	["MH-9","B_Heli_Light_01_F"],
	["Су-25СМ","HS_Su25SM_vvs"],
	["Ми-8MT","RHS_Mi8mt_vv"],
	["Ми-24В","RHS_Mi24V_vvs"],
	["Ка-52","RHS_Ka52_vvs"],
	["Ка-60","rhs_ka60_c"],
	["Лодка","B_G_Boat_Transport_01_F"],
	["Десантный катер","O_Boat_Armed_01_hmg_F"],
	["Мед. машина","I_Truck_02_medical_F"],
	["Рем. машина","I_Truck_02_box_F"],
	["Машина с боеприпасами","I_Truck_02_ammo_F"],
	["Заправщик","I_Truck_02_fuel_F"]		
];